// .dev/floor/capability-catalog-core.test.mjs — hermetic tests for the shared catalog core.
import { test } from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, rmSync, symlinkSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";
import {
  enumerateCapabilities,
  renderPage,
  renderIndex,
  buildCatalog,
  listCommittedPages,
  OUT_DIR,
  README_PATH,
  enumerateContracts,
  enumerateCommands,
  enumerateHooks,
  countFloorCheckers,
  extractCurrentState,
  renderReadmeCurrentState,
  spliceCurrentState,
} from "./capability-catalog-core.mjs";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(HERE, "..", "..");

function makeRepo() {
  return mkdtempSync(join(tmpdir(), "pharn-cat-core-"));
}

// --- fixtures for the README `## Current state` block -------------------------------------------

const MARK_BEGIN =
  "<!-- CURRENT-STATE:BEGIN — GENERATED by .dev/floor/gen-capability-catalog.mjs. DO NOT EDIT BETWEEN MARKERS. Regenerate: npm run docs:generate -->";
const MARK_END = "<!-- CURRENT-STATE:END -->";
const readmeWith = (inner) => `# Fixture\n\n## Current state\n\nIntro prose.\n\n${MARK_BEGIN}\n${inner}${MARK_END}\n\nTail prose.\n`;

/** Create the four directories renderReadmeCurrentState enumerates. */
function surface(root, opts = {}) {
  const {
    contracts = ["finding-shape.md", "eval-format.md"],
    commands = ["pharn-spec.md", "pharn-plan.md", "pharn-dev-plan.md"],
    hooks = ["protect-trusted-paths.cjs", "protect-trusted-paths.test.cjs"],
    floor = ["validate.mjs", "check-spec.mjs", "validate.test.mjs"],
  } = opts;
  const put = (rel, names, body) => {
    mkdirSync(join(root, rel), { recursive: true });
    for (const n of names) writeFileSync(join(root, rel, n), body);
  };
  // No `role:` frontmatter anywhere here, so none of these is ever counted as a capability.
  put("pharn/pharn-contracts", contracts, "# a contract\n");
  put(".claude/commands", commands, "# a command\n");
  put(".claude/hooks", hooks, "// a hook\n");
  put("pharn/floor", floor, "// a checker\n");
  writeFileSync(join(root, README_PATH), readmeWith("\n\n"));
}

// Write a capability at <root>/<dirRel>/<base>.md with the given frontmatter map + body.
function cap(root, dirRel, base, fm, body) {
  const dir = join(root, dirRel);
  mkdirSync(dir, { recursive: true });
  const fmLines = Object.entries(fm).map(([k, v]) => `${k}: ${Array.isArray(v) ? `[${v.map((x) => `"${x}"`).join(", ")}]` : v}`);
  writeFileSync(join(dir, `${base}.md`), `---\n${fmLines.join("\n")}\n---\n\n${body}\n`);
}

test("enumerate: role-order then slug, excludes non-role + excluded segments, no readdir dependence", () => {
  const root = makeRepo();
  try {
    // Created in non-sorted order on purpose; enumerate must still return the fixed sorted order.
    cap(
      root,
      "pharn/pharn-review/zzz",
      "zzz",
      { name: "zzz", role: "lens", kind: "pharn-owned", version: "0.1.0", applies: ["universal"] },
      "# zzz — flags zzz"
    );
    cap(
      root,
      "pharn/pharn-review/aaa",
      "aaa",
      { name: "aaa", role: "lens", kind: "pharn-owned", version: "0.1.0", applies: ["universal"] },
      "# aaa — flags aaa"
    );
    cap(
      root,
      "pharn/pharn-pipeline/grillers/gg",
      "gg",
      { name: "gg", role: "griller", kind: "pharn-owned", version: "0.1.0", applies: ["universal"] },
      "# gg — asks gg"
    );
    cap(
      root,
      "pharn/pharn-core/skl",
      "skl",
      { name: "skl", role: "skill", kind: "pharn-owned", version: "0.1.0", applies: ["universal"] },
      "# skl — does skl"
    );
    // Ignored: no-role md, an eval fixture, an excluded-segment md, a docs page.
    writeFileSync(join(root, "pharn/pharn-review/aaa", "notes.md"), "# not a capability\n");
    mkdirSync(join(root, ".dev/floor"), { recursive: true });
    writeFileSync(join(root, ".dev/floor/x.md"), "---\nrole: lens\n---\n# x — excluded\n");
    mkdirSync(join(root, "docs/capabilities"), { recursive: true });
    writeFileSync(join(root, "docs/capabilities/aaa.md"), "generated page — must not be re-ingested\n");

    const caps = enumerateCapabilities(root);
    assert.deepEqual(
      caps.map((c) => c.slug),
      ["gg", "aaa", "zzz", "skl"]
    );
    assert.deepEqual(
      caps.map((c) => c.role),
      ["griller", "lens", "lens", "skill"]
    );
    assert.equal(caps[1].tagline, "flags aaa"); // em-dash prefix stripped
    assert.equal(caps[1].srcRel, "pharn/pharn-review/aaa/aaa.md");
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("renderPage: full fields, GENERATED header names source, source link + install note", () => {
  const root = makeRepo();
  try {
    cap(
      root,
      "pharn/pharn-review/injection",
      "injection",
      {
        name: "injection",
        role: "lens",
        kind: "pharn-owned",
        version: "0.1.0",
        applies: ["universal"],
        coupling: "agnostic",
        enforces: ["P2"],
        model_tier: "sonnet",
      },
      "# injection — read untrusted CODE, flag concat into a sink"
    );
    const [c] = enumerateCapabilities(root);
    const page = renderPage(c);
    assert.match(page, /^<!-- GENERATED by \.dev\/floor\/gen-capability-catalog\.mjs from pharn\/pharn-review\/injection\/injection\.md /);
    assert.match(page, /# injection\n/);
    assert.match(page, /\| Role \| lens \|/);
    assert.match(page, /\| Coupling \| agnostic \|/);
    assert.match(page, /\| Enforces \| P2 \|/);
    assert.match(page, /## What it flags\n\nread untrusted CODE, flag concat into a sink\n/);
    assert.match(page, /\[`pharn\/pharn-review\/injection\/injection\.md`\]\(\.\.\/\.\.\/pharn\/pharn-review\/injection\/injection\.md\)/);
    // The install footer. Retargeted in 3.1.2: this pinned `No install command yet`, a claim that expired
    // when `@pharn-dev/pharn` was published, and the pin is what made the stale sentence load-bearing —
    // a test asserting a false claim actively resists its correction (lessons-learned L33).
    // Pinned as TWO independent assertions on purpose: the positive one would still pass if the old
    // sentence were appended alongside the new one, so the negative one is the half that makes the
    // REPLACEMENT verifiable rather than merely the addition.
    assert.match(page, /PHARN installs with `npx @pharn-dev\/pharn@latest init`/);
    assert.ok(!/No install command yet/.test(page), "the expired install claim must not survive anywhere on the page");
    // It is ONE line: the renderer emits no newline inside the footer, and a wrap would change the bytes
    // of all 36 generated pages. Asserted rather than trusted, since the plan specified it wrapped.
    const footer = page.trimEnd().split("\n").at(-1);
    assert.match(footer, /^_PHARN installs with .*documents the source file linked above\._$/);
    // A generated page must NOT open with a `---` role frontmatter block (else validate.mjs misclassifies it).
    assert.ok(!page.startsWith("---"));
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("renderPage: sparse frontmatter + missing H1 render em-dashes and the no-summary note", () => {
  const root = makeRepo();
  try {
    cap(
      root,
      "pharn/pharn-core/skl",
      "skl",
      { role: "skill", kind: "pharn-owned", version: "0.1.0", applies: ["universal"] },
      "no heading here"
    );
    const [c] = enumerateCapabilities(root);
    const page = renderPage(c);
    assert.match(page, /# skl\n/); // name falls back to slug
    assert.match(page, /\| Coupling \| — \|/);
    assert.match(page, /\| Enforces \| — \|/);
    assert.match(page, /\| Model tier \| — \|/);
    assert.match(page, /## What it does\n\n_\(no summary line in source\)_\n/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("renderIndex: grouped by role with counts, sorted lines, empty groups skipped", () => {
  const root = makeRepo();
  try {
    cap(
      root,
      "pharn/pharn-review/bbb",
      "bbb",
      { name: "bbb", role: "lens", kind: "pharn-owned", version: "0.1.0", applies: ["universal"] },
      "# bbb — flags bbb"
    );
    cap(
      root,
      "pharn/pharn-review/aaa",
      "aaa",
      { name: "aaa", role: "lens", kind: "pharn-owned", version: "0.1.0", applies: ["universal"] },
      "# aaa — flags aaa"
    );
    cap(
      root,
      "pharn/pharn-pipeline/grillers/gg",
      "gg",
      { name: "gg", role: "griller", kind: "pharn-owned", version: "0.1.0", applies: ["universal"] },
      "# gg — asks gg"
    );
    const idx = renderIndex(enumerateCapabilities(root));
    assert.match(idx, /^<!-- GENERATED by/);
    assert.match(idx, /# Capability catalog\n/);
    assert.match(idx, /3 capabilities, generated/);
    assert.match(idx, /## Grillers \(1\)\n\n- \[gg\]\(gg\.md\) — asks gg\n/);
    assert.match(idx, /## Lenses \(2\)\n\n- \[aaa\]\(aaa\.md\) — flags aaa\n- \[bbb\]\(bbb\.md\) — flags bbb\n/);
    assert.ok(!/## Skills/.test(idx)); // empty group skipped
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("buildCatalog is idempotent (byte-identical on a second run) and includes README + one page each", () => {
  const root = makeRepo();
  try {
    cap(
      root,
      "pharn/pharn-review/aaa",
      "aaa",
      { name: "aaa", role: "lens", kind: "pharn-owned", version: "0.1.0", applies: ["universal"] },
      "# aaa — flags aaa"
    );
    cap(
      root,
      "pharn/pharn-pipeline/grillers/gg",
      "gg",
      { name: "gg", role: "griller", kind: "pharn-owned", version: "0.1.0", applies: ["universal"] },
      "# gg — asks gg"
    );
    const a = buildCatalog(root);
    const b = buildCatalog(root);
    assert.deepEqual([...a.files.entries()], [...b.files.entries()]);
    assert.deepEqual([...a.files.keys()].sort(), [`${OUT_DIR}/README.md`, `${OUT_DIR}/aaa.md`, `${OUT_DIR}/gg.md`]);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("enumerate throws on a duplicate page slug (fail-closed, P5)", () => {
  const root = makeRepo();
  try {
    cap(
      root,
      "pharn/pharn-review/dup",
      "dup",
      { name: "one", role: "lens", kind: "pharn-owned", version: "0.1.0", applies: ["universal"] },
      "# one — a"
    );
    cap(
      root,
      "pharn/pharn-pipeline/grillers/dup",
      "dup",
      { name: "two", role: "griller", kind: "pharn-owned", version: "0.1.0", applies: ["universal"] },
      "# two — b"
    );
    assert.throws(() => enumerateCapabilities(root), /duplicate page slug "dup"/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("listCommittedPages: absent OUT_DIR yields empty list", () => {
  const root = makeRepo();
  try {
    assert.deepEqual(listCommittedPages(root), []);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

// ================================================================================================
// The README `## Current state` block (the second generated artifact).
// ================================================================================================

test("enumerators: extensions stripped, prefix split, tests excluded, sorted (not readdir order)", () => {
  const root = makeRepo();
  try {
    surface(root, {
      contracts: ["zeta.md", "alpha.md"],
      commands: ["pharn-verify.md", "pharn-dev-ship.md", "pharn-build.md", "pharn-dev-build.md", "not-a-pharn-command.md"],
      hooks: ["zz-hook.cjs", "aa-hook.cjs", "aa-hook.test.cjs"],
      floor: ["zz.mjs", "aa.mjs", "aa.test.mjs", "notes.md"],
    });
    assert.deepEqual(enumerateContracts(root), ["alpha", "zeta"]);
    assert.deepEqual(enumerateCommands(root), {
      product: ["pharn-build", "pharn-verify"],
      dev: ["pharn-dev-build", "pharn-dev-ship"],
    });
    // `not-a-pharn-command.md` lacks the `pharn-` prefix; `*.test.*` and a non-.mjs are excluded.
    assert.deepEqual(enumerateHooks(root), ["aa-hook.cjs", "zz-hook.cjs"]);
    assert.equal(countFloorCheckers(root), 2);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("enumerators: a DIRECTORY or SYMLINK whose NAME matches the predicate is not counted as a file", () => {
  const root = makeRepo();
  try {
    surface(root, { contracts: ["real.md"], commands: ["pharn-spec.md"], hooks: ["real.cjs"], floor: ["real.mjs"] });
    // Each predicate tests only the name, so without a type test these would inflate every count —
    // the README would assert a number no file on disk backs. `pharn/floor/test-fixtures/` is the live
    // instance of this shape; it escapes today only because it happens not to end in `.mjs`.
    mkdirSync(join(root, "pharn/pharn-contracts/notes.md"));
    mkdirSync(join(root, ".claude/commands/pharn-old.md"));
    mkdirSync(join(root, ".claude/hooks/vendor.cjs"));
    mkdirSync(join(root, "pharn/floor/scratch.mjs"));
    symlinkSync(join(root, "pharn/floor/real.mjs"), join(root, "pharn/floor/link.mjs"));

    assert.deepEqual(enumerateContracts(root), ["real"]);
    assert.deepEqual(enumerateCommands(root), { product: ["pharn-spec"], dev: [] });
    assert.deepEqual(enumerateHooks(root), ["real.cjs"]);
    assert.equal(countFloorCheckers(root), 1);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("render: every role renders including the ZERO ones, skill named with its directory", () => {
  const root = makeRepo();
  try {
    surface(root);
    cap(
      root,
      "pharn/pharn-review/aaa",
      "aaa",
      { name: "aaa", role: "lens", kind: "pharn-owned", version: "0.1.0", applies: ["universal"] },
      "# aaa — flags aaa"
    );
    cap(
      root,
      "pharn/pharn-core/seam-resolver",
      "seam-resolver",
      { name: "seam-resolver", role: "skill", kind: "pharn-owned", version: "0.1.0", applies: ["universal"] },
      "# seam-resolver — does resolution"
    );
    const block = renderReadmeCurrentState(root);

    assert.ok(block.startsWith(MARK_BEGIN), "region opens with the BEGIN marker line");
    assert.ok(block.endsWith(MARK_END), "region closes with the END marker line");
    assert.match(block, /\*\*Capabilities — 2 built\*\*/);
    // The whole enum renders: zero-instance roles say 0 rather than vanishing (P0).
    assert.match(block, /\*\*0\*\* grillers/);
    assert.match(block, /\*\*1\*\* lens,/); // singular noun at count 1
    assert.match(block, /\*\*1\*\* skill \(`pharn\/pharn-core\/seam-resolver\/`\)/);
    assert.match(block, /\*\*0\*\* validators, \*\*0\*\* verifiers, \*\*0\*\* auditors/);
    assert.match(block, /\*\*Contracts — 2\*\*/);
    assert.match(block, /\*\*Product commands — 2\*\* \(`\.claude\/commands\/`\): `\/pharn-plan`, `\/pharn-spec`/);
    assert.match(block, /\*\*Dev-apparatus commands — 1\*\*/);
    assert.match(block, /\*\*Hook scripts — 1\*\*/); // the .test.cjs is excluded
    assert.match(block, /\*\*Floor checkers — 2\*\* `\.mjs`/);
    // Deterministic: no timestamp, and a second render is byte-identical.
    assert.equal(renderReadmeCurrentState(root), block);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("render: fails closed on a missing enumerated directory rather than rendering a 0", () => {
  const root = makeRepo();
  try {
    surface(root);
    rmSync(join(root, ".claude/hooks"), { recursive: true, force: true });
    assert.throws(() => renderReadmeCurrentState(root), /expected directory is missing or unreadable: \.claude\/hooks/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("render: fails closed on a basename that is not inert markdown", () => {
  const root = makeRepo();
  try {
    surface(root, { contracts: ["ok.md", "we|ird.md"] });
    assert.throws(() => renderReadmeCurrentState(root), /unsafe basename in pharn\/pharn-contracts/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("render: fails closed on an unsafe DIRECTORY segment of a rendered skill path", () => {
  const root = makeRepo();
  try {
    surface(root);
    // Capability paths come from the walk, not listDir — so this segment never met SAFE_BASENAME.
    // A backtick would close the code span it is rendered into and spill into live README markdown.
    cap(root, "pharn/pharn-core/ev`il|dir", "s", { name: "s", role: "skill", version: "0.1.0" }, "# s — does s");
    assert.throws(() => renderReadmeCurrentState(root), /unsafe path segment "ev`il\|dir" in capability path/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("render: a repo-root capability renders an empty parent dir rather than throwing", () => {
  const root = makeRepo();
  try {
    surface(root);
    cap(root, ".", "s", { name: "s", role: "skill", version: "0.1.0" }, "# s — does s");
    assert.match(renderReadmeCurrentState(root), /\*\*1\*\* skill \(``\)/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("extract: locates the region including both marker lines", () => {
  const text = readmeWith("\n- body\n\n");
  const { region } = extractCurrentState(text);
  assert.ok(region.startsWith(MARK_BEGIN));
  assert.ok(region.endsWith(MARK_END));
  assert.match(region, /- body/);
});

test("extract: throws distinctly on missing, duplicated, and inverted markers (fail-closed, P5)", () => {
  assert.throws(() => extractCurrentState("# no markers here\n"), /no <!-- CURRENT-STATE:BEGIN/);
  assert.throws(() => extractCurrentState(`${MARK_BEGIN}\n\nbody\n`), /no <!-- CURRENT-STATE:END/);
  assert.throws(() => extractCurrentState(`${MARK_BEGIN}\n${MARK_BEGIN}\n${MARK_END}\n`), /2 BEGIN markers found/);
  assert.throws(() => extractCurrentState(`${MARK_BEGIN}\n${MARK_END}\n${MARK_END}\n`), /2 END markers found/);
  assert.throws(() => extractCurrentState(`${MARK_END}\n\n${MARK_BEGIN}\n`), /inverted/);
});

test("splice: round-trips, keeps one blank line each side, preserves prose, and is idempotent", () => {
  const root = makeRepo();
  try {
    surface(root);
    const block = renderReadmeCurrentState(root);
    const once = spliceCurrentState(readmeWith("\n\n"), block);

    assert.equal(extractCurrentState(once).region, block, "what was spliced in is what comes back out");
    assert.match(once, /Intro prose\.\n\n<!-- CURRENT-STATE:BEGIN/);
    assert.match(once, /CURRENT-STATE:END -->\n\nTail prose\./);
    assert.match(once, /^# Fixture\n/); // untouched hand prose survives
    assert.equal(spliceCurrentState(once, block), once, "splicing an already-current README is a no-op");

    // Ragged whitespace around the markers is normalised to exactly one blank line, so the generator
    // converges in one pass instead of drifting forever.
    const ragged = `# F\n\nIntro.\n\n\n\n${MARK_BEGIN}\n\nstale\n\n${MARK_END}\n\n\n\nTail.\n`;
    const fixed = spliceCurrentState(ragged, block);
    assert.equal(fixed, `# F\n\nIntro.\n\n${block}\n\nTail.\n`);
    assert.equal(spliceCurrentState(fixed, block), fixed);

    // A region at end-of-file still ends the file with exactly one newline.
    assert.equal(spliceCurrentState(`# F\n\n${MARK_BEGIN}\n${MARK_END}\n`, block), `# F\n\n${block}\n`);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("splice: propagates the marker throw — the generator never invents or relocates a marker", () => {
  const root = makeRepo();
  try {
    surface(root);
    const block = renderReadmeCurrentState(root);
    assert.throws(() => spliceCurrentState("# README with no markers\n", block), /no <!-- CURRENT-STATE:BEGIN/);
    assert.throws(() => spliceCurrentState(`${MARK_BEGIN}\n${MARK_BEGIN}\n${MARK_END}\n`, block), /2 BEGIN markers/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

// The block is spliced into a README that STAYS under prettier + markdownlint (README.md is not
// ignored by either tool). If the renderer emitted anything either tool would rewrite, `npm run check`
// would fight `npm run docs:generate` forever. Run the repo's OWN binaries and the repo's OWN rules.
//
// This is the one test here that needs the DEV toolchain, and those binaries exist only after
// `npm ci`. The `floor` workflow (.github/workflows/floor.yml) runs this suite on Node stdlib alone
// — deliberately, to prove the floor carries zero dependencies — so there both spawns are an ENOENT
// (status null, stdout/stderr undefined). Skip when a binary is absent instead of reporting that as
// a style failure. The gate still runs wherever the toolchain exists: local `npm test`, and ci.yml's
// Test step, which is itself conditioned on a successful install. A spawn that fails WITH the binary
// present stays a failure (assert.ifError) — a broken toolchain never launders into a pass.
const devBin = (name) => join(REPO_ROOT, "node_modules/.bin", name);
const missingBins = ["prettier", "markdownlint-cli2"].filter((name) => !existsSync(devBin(name)));

test(
  "style: a spliced README passes the repo's prettier and markdownlint unchanged",
  { skip: missingBins.length > 0 && `dev toolchain not installed (missing ${missingBins.join(", ")}) — run \`npm ci\`` },
  () => {
    const root = makeRepo();
    try {
      surface(root);
      const file = join(root, README_PATH);
      writeFileSync(file, spliceCurrentState(readmeWith("\n\n"), renderReadmeCurrentState(root)));

      const pretty = spawnSync(devBin("prettier"), ["--check", file], { encoding: "utf8" });
      assert.ifError(pretty.error);
      assert.equal(pretty.status, 0, `prettier would rewrite the spliced README:\n${pretty.stdout}${pretty.stderr}`);

      // Reuse the repo's rule set (minus its repo-wide globs) so these assertions cannot drift from it.
      const jsonc = readFileSync(join(REPO_ROOT, ".markdownlint-cli2.jsonc"), "utf8");
      const rules = JSON.parse(jsonc.replace(/^\s*\/\/.*$/gm, "").replace(/,(\s*[}\]])/g, "$1")).config;
      const cfg = join(root, ".markdownlint-cli2.jsonc");
      writeFileSync(cfg, JSON.stringify({ config: rules }));
      const mdl = spawnSync(devBin("markdownlint-cli2"), ["--config", cfg, file], { encoding: "utf8" });
      assert.ifError(mdl.error);
      assert.equal(mdl.status, 0, `markdownlint flagged the spliced README:\n${mdl.stdout}${mdl.stderr}`);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  }
);
